/**
 * Case Profile Schema
 * 
 * Structured representation of an immigration case, generated by CaseAnalyzer agent.
 * This profile is passed to downstream agents (AuditManager, Detective, Strategist, Gatekeeper).
 */

export type TaskType = "RISK_AUDIT" | "DOCUMENT_LIST" | "INTERVIEW_PREP" | "LOVE_STORY" | "CUSTOM"
export type AuditTier = "guest" | "pro" | "ultra"
export type UrgencyLevel = "low" | "medium" | "high"
export type ApplicationType = "spousal" | "study" | "work" | "refugee" | "family" | "other"
export type ImmigrationStatus = "citizen" | "permanent_resident" | "indian_status"
export type CurrentStatus = "visitor" | "worker" | "student" | "none"
export type RelationshipType = "marriage" | "common_law" | "conjugal"
export type EndReason = "divorce" | "death" | "annulment"
export type EvidenceCategory = "identity" | "relationship" | "financial" | "travel" | "other"
export type DocumentNature = "narrative" | "structured" | "simple"
export type RedFlagCategory = "relationship" | "documentation" | "immigration" | "financial" | "background" | "procedural"
export type Severity = "low" | "medium" | "high" | "critical"
export type CommunicationFrequency = "daily" | "weekly" | "monthly" | "rarely"

/**
 * Document Purpose Classification
 * 
 * Distinguishes between documents intended for current submission vs historical reference.
 * This prevents misinterpretation of old forms (e.g., IMM 5257 in a work permit case).
 * 
 * @since 2026-01-28 - Document purpose disambiguation feature
 */
export type DocumentPurpose = 
  | "current_submission"    // Document to be submitted with current application
  | "historical_reference"  // Previous application, for information extraction only
  | "supporting_evidence"   // Evidence supporting the application (not a form)
  | "unknown"               // Requires user clarification

export interface DocumentPurposeInfo {
  /** Classified purpose of this document */
  purpose: DocumentPurpose
  
  /** Why this purpose was assigned (for audit trail) */
  reason: string
  
  /** If true, system detected ambiguity and needs user confirmation */
  requires_confirmation: boolean
  
  /** User's confirmed purpose (set after confirmation) */
  confirmed_purpose?: DocumentPurpose
  
  /** User's explanation (if provided during confirmation) */
  user_note?: string
}

export interface Intent {
  task_type: TaskType
  tier: AuditTier
  urgency?: UrgencyLevel
  specific_concerns?: string[]
}

export interface Form {
  type: string // e.g., "IMM0008", "IMM1344"
  filename: string
  path: string
  xfa_fields?: Record<string, unknown>
  page_count?: number
  purpose_info?: DocumentPurposeInfo
}

export interface Evidence {
  category: EvidenceCategory
  filename: string
  path: string
  file_type?: "pdf" | "docx" | "doc" | "jpg" | "jpeg" | "png" | "other"
  document_nature?: DocumentNature
  summary?: string
  full_text_ref?: string
  purpose_info?: DocumentPurposeInfo
}

export interface DocumentStorage {
  extracted_docs_path: string
}

export interface DocumentConfirmationRequest {
  filename: string
  form_type?: string
  detected_purpose: DocumentPurpose
  reason: string
  suggested_options: DocumentPurpose[]
}

export interface Documents {
  total_files: number
  extracted_count: number
  failed_count: number
  forms: Form[]
  evidence: Evidence[]
  storage?: DocumentStorage
  pending_confirmations?: DocumentConfirmationRequest[]
}

export interface Address {
  street?: string
  city?: string
  province?: string
  postal_code?: string
}

export interface Employment {
  current_employer?: string
  occupation?: string
  monthly_income?: number
}

export interface MaritalHistoryEntry {
  spouse_name: string
  relationship_start: string // ISO date
  relationship_end?: string // ISO date
  end_reason?: EndReason
}

export interface PreviousSponsorship {
  sponsored_person: string
  relationship: string
  date: string // ISO date
}

export interface Sponsor {
  name: string
  family_name?: string
  given_name?: string
  dob?: string // ISO date
  status: ImmigrationStatus
  uci?: string
  address?: Address
  employment?: Employment
  marital_history?: MaritalHistoryEntry[]
  previous_sponsorships?: PreviousSponsorship[]
}

export interface Passport {
  number?: string
  issue_date?: string // ISO date
  expiry_date?: string // ISO date
}

export interface Applicant {
  name: string
  family_name?: string
  given_name?: string
  dob?: string // ISO date
  nationality: string
  uci?: string
  current_status_in_canada?: CurrentStatus
  passport?: Passport
  marital_history?: MaritalHistoryEntry[]
}

export interface Separation {
  start: string // ISO date
  end?: string // ISO date
  reason?: string
}

export interface Timeline {
  first_met?: string // ISO date
  courtship_start?: string // ISO date
  cohabitation_start?: string // ISO date
  marriage_date?: string // ISO date
  separations?: Separation[]
}

export interface Ceremony {
  held: boolean
  date?: string // ISO date
  location?: string
  attendees?: number
  reason_if_not_held?: string
}

export interface Relationship {
  type: RelationshipType
  timeline: Timeline
  ceremony?: Ceremony
  cohabiting?: boolean
  communication_frequency?: CommunicationFrequency
}

export interface Dependent {
  name: string
  dob: string // ISO date
  relationship: string
  accompanying: boolean
}

export interface RedFlag {
  category: RedFlagCategory
  severity: Severity
  description: string
  evidence?: string
}

export interface Completeness {
  critical_fields_present: boolean
  missing_documents?: string[]
  warnings?: string[]
}

/**
 * Refusal Analysis (Study Permit)
 * 
 * Analyzes refusal letter to determine if Officer Decision Notes (ODN) are available.
 * Since October 2025, IRCC includes ODN directly in IMM 0276 form, eliminating the
 * need to request GCMS notes for reconsideration.
 * 
 * @since 2026-01-26 - IMM 0276 ODN policy update
 */
export interface RefusalAnalysis {
  /** Whether a refusal letter exists */
  has_refusal_letter: boolean
  
  /** Refusal date (ISO format) */
  refusal_date?: string
  
  /** Whether IMM 0276 form is present (2025-10+) */
  has_imm0276: boolean
  
  /** Whether Officer Decision Notes are included in IMM 0276 */
  has_odn: boolean
  
  /** Full ODN content extracted from IMM 0276 */
  odn_content?: string
  
  /** Parsed officer concerns from ODN */
  officer_concerns?: string[]
  
  /** Whether GCMS notes are needed (true if no ODN available) */
  needs_gcms: boolean
  
  /** IMM 0276 form version (e.g., "10-2025") */
  imm0276_version?: string
}

/**
 * Complete Case Profile
 * 
 * Generated by CaseAnalyzer agent after extracting and analyzing case documents.
 */
export interface CaseProfile {
  case_id: string
  application_type: ApplicationType
  intent: Intent
  documents: Documents
  sponsor: Sponsor
  applicant: Applicant
  relationship: Relationship
  dependents?: Dependent[]
  red_flags?: RedFlag[]
  completeness: Completeness
  refusal_analysis?: RefusalAnalysis
}

/**
 * Validation helper: Check if profile has all critical fields
 */
export function validateCaseProfile(profile: Partial<CaseProfile>): {
  valid: boolean
  missing: string[]
} {
  const required = [
    "case_id",
    "application_type",
    "intent",
    "documents",
    "sponsor",
    "applicant",
    "relationship",
    "completeness",
  ]

  const missing: string[] = []

  for (const field of required) {
    if (!profile[field as keyof CaseProfile]) {
      missing.push(field)
    }
  }

  // Check nested required fields
  if (profile.intent && !profile.intent.task_type) {
    missing.push("intent.task_type")
  }
  if (profile.intent && !profile.intent.tier) {
    missing.push("intent.tier")
  }
  if (profile.sponsor && !profile.sponsor.name) {
    missing.push("sponsor.name")
  }
  if (profile.sponsor && !profile.sponsor.status) {
    missing.push("sponsor.status")
  }
  if (profile.applicant && !profile.applicant.name) {
    missing.push("applicant.name")
  }
  if (profile.applicant && !profile.applicant.nationality) {
    missing.push("applicant.nationality")
  }
  if (profile.relationship && !profile.relationship.type) {
    missing.push("relationship.type")
  }

  return {
    valid: missing.length === 0,
    missing,
  }
}
